# Configuration for Travis-CI continuous integration.
#
# Copyright 2015-2019 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

---
sudo: required
dist: bionic

language: c
compiler:
  - gcc
  - clang

before_install: sudo ci/install
script: ci/test
