language: c
compiler:
  - gcc
  - clang

# Perl::Tidy installed separately to get the latest version, since it
# sometimes changes formatting rules compared to the version in Ubuntu.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cppcheck libevent-dev libkrb5-dev libpam0g-dev libperl-dev libpython-dev pkg-config libtest-minimumversion-perl libtest-perl-critic-perl libtest-pod-perl libtest-strict-perl libtest-synopsis-perl
  - sudo cpanm Perl::Tidy
env: AUTHOR_TESTING=1 C_TAP_VERBOSE=1
script: ./bootstrap && ./configure && make warnings && make check
