language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cppcheck libevent-dev libkrb5-dev libpam0g-dev pkg-config libtest-minimumversion-perl libtest-pod-perl libtest-strict-perl libtest-synopsis-perl valgrind
env: AUTHOR_TESTING=1
script: ./bootstrap && ./configure && make warnings && make check-valgrind && make check-cppcheck
